# Lines configured by zsh-newuser-install
HISTFILE=~/.config/zsh/.zhistory
HISTSIZE=100000
SAVEHIST=100000
setopt notify
unsetopt beep
bindkey -e
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/kamilc/.config/zsh/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall
